In [ ]:
import pandas as pd  # type: ignore
import numpy as np  # type: ignore

new_2Darray = np.arange(0, 20).reshape(5, 4)
print(new_2Darray)
rowLable = [f"Row-{i+1}" for i in range(new_2Darray.shape[0])]
columnLable = [f"Column*{i+1}" for i in range(new_2Darray.shape[1])]
df = pd.DataFrame(data=new_2Darray, index=rowLable, columns=columnLable)

print(type(df))
print(df.info())
print(df.describe())

print(df.head())
print(type(df[["Column*2", "Column*1"]]))
print(type(df["Column*1"]))
print(df.loc[["Row-1", "Row-2"]])
print(df.iat[2, 2])
x = list(df.iloc[:, :1].values)

print(df.iloc[:, :1].values)

print(df.isnull().sum())
mf = pd.DataFrame(
    {
        "A": [1, np.nan, 3, np.nan, 5],
        "B": [np.nan, 2, np.nan, 4, 5],
        "C": [1, 2, np.nan, 4, np.nan],
    }
)
print(mf)
print(mf.isnull().sum())

print(mf.where(mf.isnull()))

print("                                             ")
print("       *******************************")
print("-------------------------------------------")
print("       *******************************")
print("                                             ")
print(df.loc[["Row-1", "Row-2"], ["Column*2", "Column*3"]])
print(df)
print(df["Column*1"].value_counts())
print(df["Column*1"].unique())
print(df > 5)
print(df%2==0)
print("                                             ")
print("       *******************************")
print("-------------------------------------------")
print("       *******************************")
print("                                             ")
print(df["Column*3"]>9)
print(df[df["Column*3"]>9])
print("-------------------------------------------")